CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;

CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);


---------- PART 1: Customer & Inventory Filtering

-- Show all customers from Bengaluru?
select *
from customers
where city = "Bengaluru";

-- Show customers who signed up after ‘2025-01-01’.
select *
from customers
where signup_date > "2025-01-01";

-- Q3. Find customers from Mumbai and Hyderabad.
select * 
from customers
where city in ("Mumbai","Hyderabad");

-- Q4. Show products belonging to the Electronics category.
select *
from products
where category = "Electronics";

-- Q5. Find products priced above 40000.
select *
from products
where price > "40000";

-- Q6. Show products where stock is less than 20.
select *
from products
where stock < "20";

-- Q7. Find products with stock between 50 and 100.
select *
from products
where stock between 50 and 100;

-- Q8. Show customers whose names start with ‘A’.
select * 
from customers
where customer_name like "A%";

-- Q9. Find products whose names contain ‘Premium’.
select * 
from products
where product_name like "%premium%";

-- Q10. Show customers registered during the year 2025.
select * 
from customers
where signup_date between "2025-01-01" and "2025-12-31";


---------- PART 2: Revenue & Sales Analysis

-- Q11. Find total revenue generated by each category.
select category,sum(price) as Total_Revenue
from products
group by category;

-- Q12. Find total quantity sold for each product.
select p.product_name,sum(o.quantity) as Total_quantity_sold
from products p
join order_items o
on p.product_id = o.product_id
group by p.product_name;

-- Q13. Find total orders under each order status.
select status,count(order_id) as Total_Order
from orders
group by status;

-- Q14. Find total revenue generated through each payment method.
select o.payment_method, sum(oi.quantity * oi.unit_price) as Total_revenue
from orders o
join order_items oi
on o.Order_id = oi.Order_id
group by o.payment_method;

-- Q15. Find average product price category-wise.
select category,avg(price) as Avg_Price
from products
group by category;

-- Q16. Find category-wise quantity sold.
SELECT p.category,SUM(o.quantity) AS total_quantity_sold
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.category;

-- Q17. Find monthly order count.
SELECT MONTH(order_date) AS month,COUNT(order_id) AS total_orders
FROM orders
GROUP BY MONTH(order_date);

-- Q18. Find monthly revenue trend.
SELECT MONTH(o.order_date) AS month,SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY MONTH(o.order_date);

-- Q19. Find the most commonly used payment method.
SELECT payment_method,COUNT(*) AS total_used
FROM orders
GROUP BY payment_method
ORDER BY total_used DESC
LIMIT 1;

-- Q20. Find the highest revenue-generating category.
SELECT p.category,SUM(o.quantity * o.unit_price) AS total_revenue
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.category
ORDER BY total_revenue DESC
LIMIT 1;

---------- PART 3: High-Value Business Insights

-- Q21. Find customers who placed more than 5 orders.
SELECT c.customer_name,COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING COUNT(o.order_id) > 5;

-- Q22. Find top 5 customers based on total spending.
SELECT c.customer_name,SUM(oi.quantity * oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_name
ORDER BY total_spending DESC
LIMIT 5;

-- Q23. Find products sold more than 30 times.
SELECT p.product_name,SUM(o.quantity) AS total_quantity_sold
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_name
HAVING SUM(o.quantity) > 30;

-- Q24. Find categories generating revenue greater than 500000.
SELECT p.category,SUM(o.quantity * o.unit_price) AS total_revenue
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.category
HAVING SUM(o.quantity * o.unit_price) > 500000;

-- Q25. Find cities having more than 10 customers.
SELECT city,COUNT(customer_id) AS total_customers
FROM customers
GROUP BY city
HAVING COUNT(customer_id) > 10;

-- Q26. Find the top 5 highest-selling products.
SELECT p.product_name,SUM(o.quantity) AS total_quantity_sold
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;

-- Q27. Find the top 3 most profitable products.
SELECT p.product_name,SUM(o.quantity * o.unit_price) AS total_profit
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_name
ORDER BY total_profit DESC
LIMIT 3;

-- Q28. Find customers whose spending is above average customer spending.
SELECT c.customer_name,SUM(oi.quantity * oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_name
HAVING SUM(oi.quantity * oi.unit_price) >
(SELECT AVG(customer_spending)
FROM(SELECT SUM(oi.quantity * oi.unit_price) AS customer_spending
        FROM orders o
        JOIN order_items oi
        ON o.order_id = oi.order_id
        GROUP BY o.customer_id) AS avg_table);
        
-- Q29. Find products contributing more than 10% of company revenue.
SELECT p.product_name,SUM(o.quantity * o.unit_price) AS product_revenue
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
GROUP BY p.product_name
HAVING SUM(o.quantity * o.unit_price) >
(SELECT SUM(quantity * unit_price) * 0.10
FROM order_items);

-- Q30. Find the city generating the highest revenue.
SELECT c.city,SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY total_revenue DESC
LIMIT 1;










