use ecommerce_interview;

 # Customer & Product Intelligence
 
--  Q31. Display all orders along with customer names.
SELECT 
    o.order_id,
    c.customer_name,
    o.order_date,
    o.status,
    o.payment_method
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id;

-- Q32. Find total revenue generated by each customer.
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC;


-- Q33. Find the total number of orders placed by each customer.
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC;


-- Q34. Find customers who never placed any orders.
SELECT 
    c.customer_id,
    c.customer_name
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


-- Q35. Find the latest order date for each customer.
SELECT 
    c.customer_id,
    c.customer_name,
    MAX(o.order_date) AS latest_order_date
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

-- Q36. Find product-wise revenue generated.
SELECT 
    p.product_id,
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;


-- Q37. Find products that were never sold.
SELECT 
    p.product_id,
    p.product_name
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;



-- Q38. Find products whose stock is lower than the total quantity sold.
SELECT 
    p.product_id,
    p.product_name,
    p.stock,
    SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name, p.stock
HAVING p.stock < SUM(oi.quantity);


-- Q39. Find category-wise revenue contribution percentage.
SELECT 
    p.category,
    SUM(oi.quantity * oi.unit_price) AS category_revenue,
    
    ROUND(
        (SUM(oi.quantity * oi.unit_price) * 100.0) /
        (SELECT SUM(quantity * unit_price) FROM order_items),
        2
    ) AS revenue_percentage
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue_percentage DESC;

-- Q40. Find repeat customers who ordered in multiple months.
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(DISTINCT MONTH(o.order_date)) AS active_months
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT MONTH(o.order_date)) > 1;


-- Executive-Level Analytics
-- Q41. Calculate overall company revenue.
SELECT 
    SUM(quantity * unit_price) AS overall_revenue
FROM order_items;

-- Q42. Calculate average order value.
SELECT 
    AVG(order_total) AS average_order_value
FROM (
    SELECT 
        order_id,
        SUM(quantity * unit_price) AS order_total
    FROM order_items
    GROUP BY order_id
) AS order_summary;

-- Q43. Calculate cancelled order percentage.
SELECT 
    (COUNT(CASE WHEN status = 'Cancelled' THEN 1 END) * 100.0) 
    / COUNT(*) AS cancelled_order_percentage
FROM orders;

-- Q44. Find the month with highest revenue.
SELECT 
    MONTH(order_date) AS month,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi 
ON o.order_id = oi.order_id
GROUP BY MONTH(order_date)
ORDER BY total_revenue DESC
LIMIT 1;

-- Q45. Find the month with highest order volume.
SELECT 
    MONTH(order_date) AS month,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY MONTH(order_date)
ORDER BY total_orders DESC
LIMIT 1;


-- Q46. Find the most common order status.
SELECT 
    status,
    COUNT(*) AS total_count
FROM orders
GROUP BY status
ORDER BY total_count DESC
LIMIT 1;


-- Q47. Generate a payment-method-wise revenue report.
SELECT 
    o.payment_method,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY o.payment_method
ORDER BY total_revenue DESC;


-- Q48. Generate a category-wise business summary report.

SELECT 
    p.category,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    SUM(oi.quantity) AS total_quantity_sold,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

--  Q49. Generate a city-wise customer and revenue report.

SELECT 
    c.city,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY total_revenue DESC;


-- Q50. Generate a final executive sales report containing:
SELECT 
    COUNT(DISTINCT o.order_id) AS total_orders,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    SUM(oi.quantity * oi.unit_price) AS total_revenue,
    AVG(oi.quantity * oi.unit_price) AS average_sale_value,
    SUM(oi.quantity) AS total_products_sold
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id;